- name: Create hysteria systemd service
  template:
    src: hysteria.service.j2
    dest: "/etc/systemd/system/{{ hysteria_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart hysteria

- name: Enable and start hysteria service
  systemd:
    name: "{{ hysteria_service_name }}"
    state: started
    enabled: yes

